config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'google.com',
  :user_name            => 'jemenisuresh',
  :password             => 'je2JE@22',
  :authentication       => 'plain',
  :enable_starttls_auto => true  }
